baseURL = "https://ryo-n.github.io/"
title = "ryo_n"
theme = "etch"

enableInlineShortcodes = true
Paginate = 5
preserveTaxonomyNames = true
enableRobotsTXT = true # generate robots.txt
pygmentsCodefences = true
enableEmoji = true

# Missing translations will default to this content language
defaultContentLanguage = "en"


[params]
copyright = "Copyright © 2020 ryo_n"
dark = "off"
highlight = true

[[menu.main]]
name="問題解説"
weight = 20
url = "https://www.notion.so/ry0n/2d7eed95099e45a89ba0e25ba22fa65d?v=2cc963f963444f148962fc0ebd8f1e97"
