baseURL = "https://ryo-n.github.io/"
title = "ryo_n"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""
logo=""

theme = "binario"

Paginate = 5
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

enableEmoji = true

# Missing translations will default to this content language
defaultContentLanguage = "en"

[params.info]
description = ""
title404 = "Nothing's here!"

[params.assets]
#favicon = "favicon.ico"
customCSS = ["css/custom.css"]
customJS = ["js/custom.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "ryo_n"
startYear = "2020"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006, Jan 02"
listDateFormat = "2006, Jan 02"
archiveDateFormat = "Jan 02"
hideEntryNavigation = ["page"] # boolean / array of sections
hideEntryMeta = ["page"] # boolean / array of sections
showReadingTime = true
showLastmod = true
taxonomyCloudShuffle = true
accentColor = "#ffcd00"
hideMainMenu = false

[params.sidebar]
enable = true

[params.widgets]
homepage = ["recent_posts"]
sidebar = ["about","sidebar_menu","taxonomy_cloud"]
footer = ["social_menu"]


[params.social]
github = "ryo-n"
twitter = "ryo_n_code"

[taxonomies]
tag = "tags"

[permalinks]
page = "/:slug/"

[[menu.main]]
name="問題解説"
weight = -10
url = "https://www.notion.so/ry0n/2d7eed95099e45a89ba0e25ba22fa65d?v=2cc963f963444f148962fc0ebd8f1e97"

[blackfriday]
hrefTargetBlank = true

[languages]
# edit this block for your own language
[languages.en]
lang = "en"
posts = "English"
weight = 1
